### ISSUE TITLE
requests.exceptions.HTTPError

### ISSUE THREAD

**Issue by joseph85750** [vanstinator/raincloudy#41]
Perhaps a cert error somewhere?

**Comment by tchellomello** [comment]
Hello @joseph85750, could you post the full backtrace?

**Comment by vanstinator** [comment]
I think you commented on https://github.com/tchellomello/raincloudy/issues/30 as well. Are you on the latest version of Home Assistant?

**Comment by vanstinator** [comment]
https://github.com/tchellomello/raincloudy/issues/30#issuecomment-488521174

**Comment by vanstinator** [comment]
@joseph85750 can you please share your script (with credentials redacted of course) so that I might try to reproduce this locally?

**Comment by vanstinator** [comment]
@joseph85750 do you have more than one controller or valve on your account? I started running into issues as well after I added a second controller. It'll be fixed in the next major release.

**Comment by joseph85750** [comment]
Justin:  Yes, I have one controller and 2 valves.  Up until the recent issue, I've always been able to communicate with my first valve.  But now I'm not able to do so, and get the error mentioned.Thanks!


    On Friday, May 17, 2019, 7:33:14 AM MST, Justin Vanderhooft <notifications@github.com> wrote:  
 
 
@joseph85750 do you have more than one controller or valve on your account? I started running into issues as well after I added a second controller. It'll be fixed in the next major release.

**Comment by joseph85750** [comment]
Any update on this?  As stated, I have 1 controller and 2 valves.  It was working great to monitor the 1st valve, no errors.  I was never able to check the 2nd valve, but this was a known issue.  But I now/still get the error.  Is there more I can provide?
Thanks!

**Comment by NoahJaehnert** [comment]
I also have one controller and two valves. I am running into this same issue. Is there anything I can do to help/any info I can provide to assist in getting this issue solved?

**Comment by NoahJaehnert** [comment]
Update: I actually do have two controllers AND four valves. At this time, only one controller and two valves are configured in my account. I am happy to help test however/whatever I can. Just let me know. 

After some additional testing, I noticed that in HomeAssistant, the error I am getting is possibly due to the addition of "%0A2" at the end of my faucet_serial variable. 

Original error message: [homeassistant.components.raincloud] Unable to connect to Rain Cloud service: 500 Server Error: Internal Server Error for url: https://wifiaquatimer.com/get_cu_and_fu_status?controller_serial=redacted&faucet_serial=df31%0A2

Browsing to https://wifiaquatimer.com/get_cu_and_fu_status?controller_serial=redacted&faucet_serial=df31%0A2 returns a 500 error

Browsing to https://wifiaquatimer.com/get_cu_and_fu_status?controller_serial=redacted&faucet_serial=df31 returns JSON: ""controller_status": "Online", "channel_occupied": true, "battery_percent": "99%", "rf_link": true, "current_time": "04:20 PM", "controller_serial": "redacted", ..."

**Comment by joseph85750** [comment]
> Hello @joseph85750, could you post the full backtrace?

  Sorry, I did not see this until now.   How would I get this info for you?
